import { jsPDF } from 'jspdf';
import { Invoice, Receipt, BillingSettings } from '../types';

// ─── Constants ────────────────────────────────────────────────────────────────
const PW = 210;   // A4 page width  (mm)
const PH = 297;   // A4 page height (mm)
const ML = 14;    // left margin
const MR = 14;    // right margin
const MT = 14;    // top margin
const CW = PW - ML - MR; // content width = 182 mm

// ─── Helpers ──────────────────────────────────────────────────────────────────
function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const m = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return m
    ? { r: parseInt(m[1], 16), g: parseInt(m[2], 16), b: parseInt(m[3], 16) }
    : { r: 79, g: 70, b: 229 };
}

function fmtDate(dateStr?: string): string {
  if (!dateStr) return '—';
  return new Date(dateStr).toLocaleDateString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric'
  }).toUpperCase();
}

function fmtMoney(n: number): string {
  return `Rs. ${n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function numToWords(n: number): string {
  const a = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
    'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen',
    'Seventeen', 'Eighteen', 'Nineteen'];
  const b = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  const fmt = (x: number): string => {
    if (x < 20) return a[x];
    if (x < 100) return b[Math.floor(x / 10)] + (x % 10 ? ' ' + a[x % 10] : '');
    if (x < 1000) return a[Math.floor(x / 100)] + ' Hundred' + (x % 100 ? ' ' + fmt(x % 100) : '');
    if (x < 100000) return fmt(Math.floor(x / 1000)) + ' Thousand' + (x % 1000 ? ' ' + fmt(x % 1000) : '');
    if (x < 10000000) return fmt(Math.floor(x / 100000)) + ' Lakh' + (x % 100000 ? ' ' + fmt(x % 100000) : '');
    return x.toString();
  };
  return fmt(Math.floor(n)) + ' Rupees Only';
}

function pageFooter(doc: jsPDF, practiceName: string): void {
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.2);
  doc.line(ML, PH - 10, PW - MR, PH - 10);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(170, 170, 170);
  doc.text('Generated by Profee.in', ML, PH - 5.5);
  doc.text(practiceName, PW - MR, PH - 5.5, { align: 'right' });
}

// ─── INVOICE PDF ─────────────────────────────────────────────────────────────
export function generateInvoicePDF(invoice: Invoice, settings: BillingSettings): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const tc = hexToRgb(invoice.themeColor || '#4f46e5');
  const hasGst = settings.isGstApplicable;

  // ── HEADER BANNER ──
  doc.setFillColor(tc.r, tc.g, tc.b);
  doc.rect(0, 0, PW, 20, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text('INVOICE', ML, 13);

  doc.setFontSize(11);
  doc.text(settings.practiceName.toUpperCase(), PW - MR, 10, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.text('Tax Professionals & Consultants', PW - MR, 15.5, { align: 'right' });

  let y = 28;

  // ── INVOICE META ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(140, 140, 140);
  doc.text('Invoice No.', ML, y);
  doc.text('Date', ML + 60, y);
  doc.text('Due Date', ML + 110, y);

  y += 5;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(25, 25, 25);
  doc.text(invoice.invoiceNumber, ML, y);
  doc.setFontSize(9);
  doc.text(fmtDate(invoice.date), ML + 60, y);
  doc.text(fmtDate(invoice.dueDate), ML + 110, y);

  y += 9;

  // ── DIVIDER ──
  doc.setDrawColor(tc.r, tc.g, tc.b);
  doc.setLineWidth(0.5);
  doc.line(ML, y, PW - MR, y);
  y += 7;

  // ── BILLED BY / BILLED TO ──
  const colW = CW / 2 - 4;
  const boxH = 36;

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(ML, y, colW, boxH, 2, 2, 'F');
  doc.setDrawColor(228, 232, 240);
  doc.setLineWidth(0.3);
  doc.roundedRect(ML, y, colW, boxH, 2, 2, 'S');

  doc.roundedRect(ML + colW + 8, y, colW, boxH, 2, 2, 'F');
  doc.roundedRect(ML + colW + 8, y, colW, boxH, 2, 2, 'S');

  // Left column content
  const writePartyBlock = (
    xStart: number, yStart: number,
    header: string, headerColor: { r: number; g: number; b: number },
    name: string, address: string, gstin: string, pan: string
  ) => {
    let ly = yStart + 5;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6.5);
    doc.setTextColor(headerColor.r, headerColor.g, headerColor.b);
    doc.text(header, xStart + 4, ly);
    ly += 5;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(25, 25, 25);
    doc.text(name.toUpperCase().substring(0, 30), xStart + 4, ly);
    ly += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 100, 100);
    const addrLines = doc.splitTextToSize(address || 'Address on file', colW - 10);
    doc.text(addrLines.slice(0, 2), xStart + 4, ly);
    ly += addrLines.slice(0, 2).length * 4.5 + 1;
    doc.setFontSize(7);
    if (gstin) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 100, 100);
      doc.text('GSTIN: ', xStart + 4, ly);
      doc.setFont('helvetica', 'normal');
      doc.text(gstin, xStart + 4 + 14, ly);
      ly += 4.5;
    }
    if (pan) {
      doc.setFont('helvetica', 'bold');
      doc.text('PAN: ', xStart + 4, ly);
      doc.setFont('helvetica', 'normal');
      doc.text(pan, xStart + 4 + 10, ly);
    }
  };

  writePartyBlock(ML, y, 'BILLED BY', tc,
    settings.practiceName, settings.address, settings.gstin, settings.pan);
  writePartyBlock(ML + colW + 8, y, 'BILLED TO', { r: 100, g: 100, b: 100 },
    invoice.clientName, invoice.clientAddress || '', invoice.clientGstin || 'URD', invoice.clientPan || '');

  y += boxH + 6;

  // ── SUPPLY INFO BAR ──
  doc.setFillColor(241, 245, 249);
  doc.rect(ML, y, CW, 7, 'F');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(80, 80, 80);
  doc.text(`Place of Supply: ${invoice.placeOfSupply || 'India'}`, ML + 4, y + 4.5);
  doc.text(`Country: ${invoice.countryOfSupply || 'India'}`, PW - MR - 4, y + 4.5, { align: 'right' });
  y += 12;

  // ── ITEMS TABLE ──
  type Col = { label: string; w: number; align: 'left' | 'center' | 'right' };
  const cols: Col[] = hasGst
    ? [
        { label: 'Description', w: 58, align: 'left' },
        { label: 'HSN', w: 18, align: 'center' },
        { label: 'Qty', w: 10, align: 'center' },
        { label: 'GST %', w: 14, align: 'center' },
        { label: 'Taxable', w: 26, align: 'right' },
        { label: 'SGST', w: 18, align: 'right' },
        { label: 'CGST', w: 18, align: 'right' },
        { label: 'Amount', w: 20, align: 'right' },
      ]
    : [
        { label: 'Description', w: 82, align: 'left' },
        { label: 'HSN', w: 22, align: 'center' },
        { label: 'Qty', w: 18, align: 'center' },
        { label: 'Taxable Amount', w: 36, align: 'right' },
        { label: 'Amount', w: 24, align: 'right' },
      ];

  const tHeaderH = 8;
  const tRowH = 12;

  // Table header row
  doc.setFillColor(tc.r, tc.g, tc.b);
  doc.rect(ML, y, CW, tHeaderH, 'F');
  let cx = ML;
  cols.forEach(col => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(255, 255, 255);
    const tx = col.align === 'right' ? cx + col.w - 2.5
      : col.align === 'center' ? cx + col.w / 2
      : cx + 3;
    doc.text(col.label.toUpperCase(), tx, y + 5.2, { align: col.align === 'right' ? 'right' : col.align === 'center' ? 'center' : 'left' });
    cx += col.w;
  });
  y += tHeaderH;

  // Table rows
  (invoice.items || []).forEach((item, idx) => {
    const taxable = (item.qty * item.rate) - (item.qty * item.rate * (invoice.discountPercent || 0) / 100);
    const gstAmt  = taxable * (item.gstPercent / 100);
    const lineTotal = taxable + gstAmt;

    if (idx % 2 === 0) {
      doc.setFillColor(249, 251, 253);
      doc.rect(ML, y, CW, tRowH, 'F');
    }
    doc.setDrawColor(230, 235, 240);
    doc.setLineWidth(0.2);
    doc.line(ML, y + tRowH, PW - MR, y + tRowH);

    const vals: string[] = hasGst
      ? [
          item.description,
          item.hsn || '',
          String(item.qty),
          `${item.gstPercent}%`,
          `Rs.${taxable.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`,
          `Rs.${(gstAmt / 2).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`,
          `Rs.${(gstAmt / 2).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`,
          `Rs.${lineTotal.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`,
        ]
      : [
          item.description,
          item.hsn || '',
          String(item.qty),
          `Rs.${taxable.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`,
          `Rs.${lineTotal.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`,
        ];

    let rx = ML;
    cols.forEach((col, ci) => {
      doc.setFont('helvetica', ci === 0 ? 'bold' : 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(40, 40, 40);
      const v = vals[ci] || '';
      if (col.align === 'right') {
        doc.text(v, rx + col.w - 2.5, y + 5, { align: 'right' });
      } else if (col.align === 'center') {
        doc.text(v, rx + col.w / 2, y + 5, { align: 'center' });
      } else {
        const lines = doc.splitTextToSize(v, col.w - 5);
        doc.text(lines[0], rx + 3, y + 5);
        if (item.subNotes && ci === 0) {
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(6.5);
          doc.setTextColor(130, 130, 130);
          doc.text(item.subNotes.substring(0, 40), rx + 3, y + 9);
        }
      }
      rx += col.w;
    });

    y += tRowH;
    if (y > PH - 85) {
      pageFooter(doc, settings.practiceName);
      doc.addPage();
      y = MT;
    }
  });

  y += 6;

  // ── TOTALS ──
  const totColX = ML + CW / 2;
  const totRows: [string, string, string?][] = [
    ['Sub Total', fmtMoney(invoice.subTotal || 0)],
    ...(invoice.discountPercent
      ? [[`Discount (${invoice.discountPercent}%)`, `- ${fmtMoney(invoice.discountAmount || 0)}`, 'rgb(16,185,129)'] as [string, string, string]]
      : []),
    ['Taxable Amount', fmtMoney(invoice.taxableAmount || 0)],
    ...(hasGst
      ? [
          ['CGST', fmtMoney(invoice.cgstTotal || 0)] as [string, string],
          ['SGST', fmtMoney(invoice.sgstTotal || 0)] as [string, string],
        ]
      : []),
  ];

  totRows.forEach(([label, val, colorStr]) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(label, totColX + 2, y);
    doc.setFont('helvetica', 'bold');
    if (colorStr) {
      doc.setTextColor(16, 185, 129);
    } else {
      doc.setTextColor(40, 40, 40);
    }
    doc.text(val, PW - MR, y, { align: 'right' });
    y += 6;
  });

  // Grand total bar
  y += 1;
  doc.setFillColor(tc.r, tc.g, tc.b);
  doc.roundedRect(totColX, y, CW / 2, 10, 1.5, 1.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.text('TOTAL', totColX + 4, y + 6.5);
  doc.setFontSize(10);
  doc.text(fmtMoney(invoice.total || 0), PW - MR - 3, y + 6.5, { align: 'right' });
  y += 14;

  // Amount in words
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7.5);
  doc.setTextColor(tc.r, tc.g, tc.b);
  doc.text(numToWords(invoice.total || 0), ML, y);
  y += 12;

  // Check for page overflow before bank/terms block
  if (y > PH - 70) {
    pageFooter(doc, settings.practiceName);
    doc.addPage();
    y = MT;
  }

  // ── BANK DETAILS + TERMS ──
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(ML, y, PW - MR, y);
  y += 6;

  const bankColW = CW / 2 - 6;

  // Bank heading
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(tc.r, tc.g, tc.b);
  doc.text('BANK & PAYMENT DETAILS', ML, y);

  // Terms heading
  doc.setTextColor(100, 100, 100);
  doc.text('TERMS & CONDITIONS', ML + bankColW + 12, y);
  y += 5;

  // Bank fields
  const bankFields: [string, string][] = [
    ['Holder', settings.bankDetails.accountHolder],
    ['Account No.', settings.bankDetails.accountNumber],
    ['IFSC', settings.bankDetails.ifsc],
    ['Bank', settings.bankDetails.bankName],
    ['Type', settings.bankDetails.accountType],
    ['UPI', settings.bankDetails.upiId],
  ].filter(([, v]) => !!v) as [string, string][];

  let bankY = y;
  bankFields.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(120, 120, 120);
    doc.text(`${label}:`, ML, bankY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(40, 40, 40);
    doc.text(value.substring(0, 28), ML + 22, bankY);
    bankY += 5;
  });

  // Terms
  let termsY = y;
  settings.terms.forEach((term, i) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    const lines = doc.splitTextToSize(`${i + 1}. ${term}`, bankColW);
    doc.text(lines[0], ML + bankColW + 12, termsY);
    termsY += 5;
  });

  y = Math.max(bankY, termsY) + 8;

  // ── SIGNATURE ──
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.2);
  doc.line(ML, y, PW - MR, y);
  y += 6;

  if (invoice.notes) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7);
    doc.setTextColor(130, 130, 130);
    const noteLines = doc.splitTextToSize(`Note: ${invoice.notes}`, bankColW);
    doc.text(noteLines.slice(0, 2), ML, y + 4);
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 100);
  doc.text('Authorized Signatory', PW - MR, y, { align: 'right' });
  doc.setLineWidth(0.3);
  doc.line(PW - MR - 38, y + 10, PW - MR, y + 10);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(50, 50, 50);
  doc.text(settings.practiceName, PW - MR, y + 14, { align: 'right' });

  pageFooter(doc, settings.practiceName);
  doc.save(`${invoice.invoiceNumber || 'Invoice'}.pdf`);
}

// ─── RECEIPT PDF ──────────────────────────────────────────────────────────────
export function generateReceiptPDF(receipt: Receipt, settings: BillingSettings): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const green = { r: 5, g: 150, b: 105 };

  // ── HEADER BANNER ──
  doc.setFillColor(green.r, green.g, green.b);
  doc.rect(0, 0, PW, 20, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text('PAYMENT RECEIPT', ML, 13);

  doc.setFontSize(11);
  doc.text(settings.practiceName.toUpperCase(), PW - MR, 10, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.text('Official Payment Confirmation', PW - MR, 15.5, { align: 'right' });

  let y = 30;

  // ── META ROW ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(140, 140, 140);
  doc.text('Receipt No.', ML, y);
  doc.text('Payment Date', ML + 70, y);
  doc.text('Transaction Ref.', ML + 130, y);

  y += 5;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(25, 25, 25);
  doc.text(receipt.receiptNumber, ML, y);
  doc.text(fmtDate(receipt.date), ML + 70, y);
  doc.setFontSize(8);
  doc.text(receipt.reference || 'N/A', ML + 130, y);

  y += 12;

  // ── MAIN CONTENT BOX ──
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(220, 225, 230);
  doc.setLineWidth(0.3);
  doc.roundedRect(ML, y, CW, 58, 3, 3, 'FD');

  // Received from
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(130, 130, 130);
  doc.text('Received From', ML + 6, y + 8);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text(receipt.clientName.toUpperCase(), ML + 6, y + 15);

  // Mode of payment
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(130, 130, 130);
  doc.text('Mode of Payment', ML + 6, y + 24);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(ML + 6, y + 26, 50, 8, 1.5, 1.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(5, 150, 105);
  doc.text(receipt.paymentMethod, ML + 10, y + 31.5);

  // Divider inside box
  doc.setDrawColor(220, 225, 230);
  doc.setLineWidth(0.2);
  doc.line(ML + 6, y + 38, PW - MR - 6, y + 38);

  // Amount
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(130, 130, 130);
  doc.text('Amount Received', ML + 6, y + 44);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(5, 150, 105);
  doc.text(fmtMoney(receipt.amount || 0), ML + 6, y + 54);

  // Practice name (right)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text(settings.practiceName, PW - MR - 6, y + 44, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(130, 130, 130);
  doc.text(settings.address ? doc.splitTextToSize(settings.address, 55)[0] : '', PW - MR - 6, y + 50, { align: 'right' });

  y += 68;

  // ── AMOUNT IN WORDS ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(130, 130, 130);
  doc.text('Amount in Words:', ML, y);
  y += 5;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(green.r, green.g, green.b);
  doc.text(numToWords(receipt.amount || 0), ML, y);
  y += 16;

  // ── SIGNATURE ──
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.2);
  doc.line(ML, y, PW - MR, y);
  y += 8;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 100, 100);
  doc.text('Authorized Signatory', PW - MR, y, { align: 'right' });
  doc.setLineWidth(0.3);
  doc.line(PW - MR - 40, y + 10, PW - MR, y + 10);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(50, 50, 50);
  doc.text(settings.practiceName, PW - MR, y + 14, { align: 'right' });

  pageFooter(doc, settings.practiceName);
  doc.save(`${receipt.receiptNumber || 'Receipt'}.pdf`);
}

// ─── LEDGER PDF ───────────────────────────────────────────────────────────────
interface LedgerEntry {
  date: string;
  ref: string;
  description: string;
  type: 'invoice' | 'receipt';
  amount: number;
  balance: number;
}

interface LedgerOptions {
  title: string;
  subtitle: string;
  dateFrom?: string;
  dateTo?: string;
  entries: LedgerEntry[];
  totalInvoiced: number;
  totalReceived: number;
  filename: string;
}

export function generateLedgerPDF(opts: LedgerOptions, settings: BillingSettings): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const indigo = { r: 79, g: 70, b: 229 };

  // ── HEADER BANNER ──
  doc.setFillColor(indigo.r, indigo.g, indigo.b);
  doc.rect(0, 0, PW, 20, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text(opts.title.toUpperCase(), ML, 13);

  doc.setFontSize(10);
  doc.text(settings.practiceName.toUpperCase(), PW - MR, 10, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.text(opts.subtitle, PW - MR, 15.5, { align: 'right' });

  let y = 30;

  // ── META ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  if (opts.dateFrom || opts.dateTo) {
    doc.text(`Period: ${opts.dateFrom || 'Start'} to ${opts.dateTo || 'Today'}`, ML, y);
  }
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, PW - MR, y, { align: 'right' });
  y += 10;

  // ── TABLE ──
  const cols = [
    { label: 'Date', w: 24 },
    { label: 'Reference', w: 32 },
    { label: 'Description', w: 60 },
    { label: 'Debit (Rs.)', w: 25 },
    { label: 'Credit (Rs.)', w: 25 },
    { label: 'Balance (Rs.)', w: 16 },
  ];

  const tHeaderH = 8;
  const tRowH = 8;

  const drawTableHeader = (startY: number) => {
    doc.setFillColor(indigo.r, indigo.g, indigo.b);
    doc.rect(ML, startY, CW, tHeaderH, 'F');
    let cx = ML;
    cols.forEach(col => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(255, 255, 255);
      doc.text(col.label.toUpperCase(), cx + 3, startY + 5.2);
      cx += col.w;
    });
    return startY + tHeaderH;
  };

  y = drawTableHeader(y);

  opts.entries.forEach((entry, idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(249, 251, 253);
      doc.rect(ML, y, CW, tRowH, 'F');
    }
    doc.setDrawColor(230, 235, 240);
    doc.setLineWidth(0.2);
    doc.line(ML, y + tRowH, PW - MR, y + tRowH);

    const debit  = entry.type === 'invoice' ? entry.amount.toLocaleString('en-IN', { minimumFractionDigits: 2 }) : '—';
    const credit = entry.type === 'receipt' ? entry.amount.toLocaleString('en-IN', { minimumFractionDigits: 2 }) : '—';
    const balStr = `${Math.abs(entry.balance).toLocaleString('en-IN', { minimumFractionDigits: 2 })} ${entry.balance >= 0 ? 'Dr' : 'Cr'}`;

    const rowVals = [entry.date, entry.ref, entry.description, debit, credit, balStr];
    let rx = ML;
    cols.forEach((col, ci) => {
      doc.setFont('helvetica', ci === 1 || ci === 0 ? 'bold' : 'normal');
      doc.setFontSize(7.5);
      if (ci === 3) doc.setTextColor(220, 38, 38);   // debit  = red
      else if (ci === 4) doc.setTextColor(5, 150, 105); // credit = green
      else if (ci === 5) doc.setTextColor(entry.balance >= 0 ? 220 : 5, entry.balance >= 0 ? 38 : 150, entry.balance >= 0 ? 38 : 105);
      else doc.setTextColor(40, 40, 40);
      const v = doc.splitTextToSize(rowVals[ci] || '', col.w - 5)[0];
      doc.text(v, rx + 3, y + 5.5);
      rx += col.w;
    });

    y += tRowH;
    if (y > PH - 40) {
      pageFooter(doc, settings.practiceName);
      doc.addPage();
      y = MT;
      y = drawTableHeader(y);
    }
  });

  y += 4;

  // ── SUMMARY ROW ──
  doc.setFillColor(30, 41, 59);
  doc.rect(ML, y, CW, 10, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text('SUMMARY', ML + 4, y + 6.5);

  const sumDebit  = opts.totalInvoiced.toLocaleString('en-IN', { minimumFractionDigits: 2 });
  const sumCredit = opts.totalReceived.toLocaleString('en-IN', { minimumFractionDigits: 2 });
  const outstanding = opts.totalInvoiced - opts.totalReceived;
  const sumBal = `${Math.abs(outstanding).toLocaleString('en-IN', { minimumFractionDigits: 2 })} ${outstanding >= 0 ? 'Dr' : 'Cr'}`;

  const sumOffsets = [24 + 32 + 60, 24 + 32 + 60 + 25, 24 + 32 + 60 + 25 + 25];
  [sumDebit, sumCredit, sumBal].forEach((v, i) => {
    doc.text(v, ML + sumOffsets[i] + 3, y + 6.5);
  });

  y += 16;

  // ── QUICK STATS ──
  const statBoxW = CW / 3 - 3;
  const stats: [string, string, number, number, number][] = [
    ['Total Invoiced', fmtMoney(opts.totalInvoiced), 220, 38, 38],
    ['Total Received', fmtMoney(opts.totalReceived), 5, 150, 105],
    ['Outstanding', fmtMoney(Math.abs(outstanding)), outstanding >= 0 ? 220 : 5, outstanding >= 0 ? 38 : 150, outstanding >= 0 ? 38 : 105],
  ];

  stats.forEach(([label, val, r, g, b], i) => {
    const sx = ML + i * (statBoxW + 4.5);
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(220, 225, 230);
    doc.setLineWidth(0.3);
    doc.roundedRect(sx, y, statBoxW, 14, 2, 2, 'FD');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(130, 130, 130);
    doc.text(label, sx + statBoxW / 2, y + 5, { align: 'center' });
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(r, g, b);
    doc.text(val, sx + statBoxW / 2, y + 11.5, { align: 'center' });
  });

  pageFooter(doc, settings.practiceName);
  doc.save(opts.filename);
}
