import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

// ─── Helpers ────────────────────────────────────────────────────────────────

const FONT = 'helvetica';
const SLATE8 = [30, 41, 59] as const;
const SLATE5 = [100, 116, 139] as const;
const SLATE3 = [203, 213, 225] as const;
const WHITE = [255, 255, 255] as const;
const LIGHT_BG = [248, 250, 252] as const;

function setFillColor(pdf: jsPDF, color: readonly [number, number, number] | [number, number, number]) {
  pdf.setFillColor(color[0], color[1], color[2]);
}
function setTextColor(pdf: jsPDF, color: readonly [number, number, number] | [number, number, number]) {
  pdf.setTextColor(color[0], color[1], color[2]);
}
function setDrawColor(pdf: jsPDF, color: readonly [number, number, number] | [number, number, number]) {
  pdf.setDrawColor(color[0], color[1], color[2]);
}

function wrapText(pdf: jsPDF, text: string, maxWidth: number): string[] {
  return pdf.splitTextToSize(text, maxWidth);
}

function inrFormat(n: number): string {
  return '₹' + (n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function addWatermark(pdf: jsPDF) {
  const pages = pdf.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    setTextColor(pdf, SLATE3);
    pdf.setFont(FONT, 'normal');
    pdf.text('Generated by Profee.in', 14, 290);
    pdf.text(`Page ${i} of ${pages}`, 196, 290, { align: 'right' });
  }
}

// Wait for all images inside an element to finish loading
async function waitForImages(el: HTMLElement): Promise<void> {
  const imgs = Array.from(el.querySelectorAll('img'));
  await Promise.all(
    imgs.map(img =>
      img.complete
        ? Promise.resolve()
        : new Promise<void>(res => {
            img.onload = () => res();
            img.onerror = () => res();
          })
    )
  );
}

// ─── Capture-based PDF (Invoice & Receipt) ───────────────────────────────────
// Captures the on-screen React template at 3× resolution so the PDF matches
// the UI design exactly, then embeds it into an A4 PDF.

async function captureElementToPDF(
  elementId: string,
  filename: string,
  marginMm = 8,
): Promise<void> {
  const el = document.getElementById(elementId);
  if (!el) throw new Error(`Element #${elementId} not found`);

  // Wait for any images (e.g. QR code) to fully load
  await waitForImages(el as HTMLElement);

  // Small delay so fonts / layout settle
  await new Promise(r => setTimeout(r, 150));

  const canvas = await html2canvas(el as HTMLElement, {
    scale: 3,                      // 3× = ~216 DPI on screen → sharp on print
    backgroundColor: '#ffffff',
    useCORS: true,
    allowTaint: false,
    logging: false,
    imageTimeout: 20000,
    onclone: (_doc: Document, cloned: HTMLElement) => {
      // Remove shadows & decorative borders so nothing clips during capture
      cloned.style.boxShadow = 'none';
      cloned.style.border = 'none';
      cloned.style.borderRadius = '0';
      cloned.querySelectorAll<HTMLElement>('[class*="shadow"]').forEach(n => {
        n.style.boxShadow = 'none';
      });
      // Keep rounded corners on inner elements (table header, boxes etc.) intact
    },
  });

  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageW = 210;
  const pageH = 297;
  const usableW = pageW - marginMm * 2;
  const usableH = pageH - marginMm * 2;
  const imgH = (canvas.height * usableW) / canvas.width;

  // Use JPEG at 0.95 quality — smaller file, still visually lossless
  const imgData = canvas.toDataURL('image/jpeg', 0.95);

  if (imgH <= usableH) {
    // Fits on one page
    pdf.addImage(imgData, 'JPEG', marginMm, marginMm, usableW, imgH);
  } else {
    // Multi-page: slice the canvas into page-height chunks
    let remainingH = imgH;
    let pageTop = 0;
    while (remainingH > 0) {
      if (pageTop > 0) pdf.addPage();
      // Position image so the correct slice falls in the visible area
      pdf.addImage(imgData, 'JPEG', marginMm, marginMm - pageTop, usableW, imgH);
      pageTop += usableH;
      remainingH -= usableH;
    }
  }

  addWatermark(pdf);
  pdf.save(filename);
}

export async function generateInvoicePDF(
  invoiceNumber: string,
): Promise<void> {
  await captureElementToPDF('invoice-capture', `${invoiceNumber || 'Invoice'}.pdf`);
}

export async function generateReceiptPDF(
  receiptNumber: string,
): Promise<void> {
  await captureElementToPDF('receipt-capture', `${receiptNumber || 'Receipt'}.pdf`, 6);
}

// ─── Ledger PDF (native jsPDF — no on-screen template to capture) ─────────────

function numberToWords(num: number): string {
  const a = ['', 'One ', 'Two ', 'Three ', 'Four ', 'Five ', 'Six ', 'Seven ', 'Eight ', 'Nine ', 'Ten ', 'Eleven ', 'Twelve ', 'Thirteen ', 'Fourteen ', 'Fifteen ', 'Sixteen ', 'Seventeen ', 'Eighteen ', 'Nineteen '];
  const b = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  const format = (n: number): string => {
    if (n < 20) return a[n];
    if (n < 100) return b[Math.floor(n / 10)] + (n % 10 !== 0 ? ' ' + a[n % 10] : '');
    if (n < 1000) return a[Math.floor(n / 100)] + 'Hundred ' + (n % 100 !== 0 ? 'And ' + format(n % 100) : '');
    if (n < 100000) return format(Math.floor(n / 1000)) + 'Thousand ' + (n % 1000 !== 0 ? format(n % 1000) : '');
    if (n < 10000000) return format(Math.floor(n / 100000)) + 'Lakh ' + (n % 100000 !== 0 ? format(n % 100000) : '');
    return n.toString();
  };
  return format(Math.floor(num)).trim() + ' Rupees Only';
}

interface LedgerEntry {
  date: string;
  ref: string;
  description: string;
  type: 'invoice' | 'receipt';
  amount: number;
  balance: number;
}

export function generateClientLedgerPDF(
  clientName: string,
  clientPan: string | undefined,
  entries: LedgerEntry[],
  totalInvoiced: number,
  totalReceived: number,
  practiceName: string,
  dateFrom?: string,
  dateTo?: string,
): void {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const W = 210;
  const margin = 14;
  const contentW = W - margin * 2;
  let y = 0;

  // ── Header ──
  setFillColor(pdf, SLATE8);
  pdf.rect(0, 0, W, 32, 'F');
  pdf.setFont(FONT, 'bold');
  pdf.setFontSize(18);
  setTextColor(pdf, WHITE);
  pdf.text('CLIENT LEDGER', margin, 16);
  pdf.setFont(FONT, 'normal');
  pdf.setFontSize(8.5);
  pdf.text(practiceName, margin, 25);
  pdf.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, W - margin, 25, { align: 'right' });

  y = 40;

  // ── Client info row ──
  setFillColor(pdf, LIGHT_BG);
  pdf.rect(margin, y, contentW, 14, 'F');
  pdf.setFont(FONT, 'bold');
  pdf.setFontSize(11);
  setTextColor(pdf, SLATE8);
  pdf.text(clientName.toUpperCase(), margin + 4, y + 6);
  pdf.setFont(FONT, 'normal');
  pdf.setFontSize(8);
  setTextColor(pdf, SLATE5);
  if (clientPan) pdf.text(`PAN: ${clientPan}`, margin + 4, y + 11);
  if (dateFrom || dateTo) {
    pdf.text(`Period: ${dateFrom || 'Start'} to ${dateTo || 'Present'}`, W - margin - 4, y + 6, { align: 'right' });
  }
  y += 20;

  // ── Table header ──
  const colWidths = [22, 28, 62, 28, 28, 14];
  const balW = 24;
  const colXs: number[] = [margin];
  for (let i = 0; i < colWidths.length - 1; i++) colXs.push(colXs[i] + colWidths[i]);
  const balX = margin + contentW - balW;

  setFillColor(pdf, SLATE8);
  pdf.rect(margin, y, contentW, 8, 'F');
  pdf.setFont(FONT, 'bold');
  pdf.setFontSize(7.5);
  setTextColor(pdf, WHITE);
  const headers = ['Date', 'Reference', 'Description', 'Debit (₹)', 'Credit (₹)', 'Balance (₹)'];
  const hAligns: ('left' | 'right' | 'center')[] = ['left', 'left', 'left', 'right', 'right', 'right'];
  headers.forEach((h, i) => {
    const hx = i < 5
      ? (hAligns[i] === 'right' ? colXs[i] + colWidths[i] - 2 : colXs[i] + 2)
      : balX + balW - 2;
    pdf.text(h, hx, y + 5.5, { align: hAligns[i] });
  });
  y += 8;

  // ── Rows ──
  pdf.setFontSize(8);
  entries.forEach((entry, idx) => {
    if (y + 10 > 272) { pdf.addPage(); y = 16; }

    const rowBg: [number, number, number] = idx % 2 === 0 ? [255, 255, 255] : [249, 250, 251];
    setFillColor(pdf, rowBg);
    pdf.rect(margin, y, contentW, 9, 'F');
    setDrawColor(pdf, [226, 232, 240]);
    pdf.setLineWidth(0.2);
    pdf.line(margin, y + 9, margin + contentW, y + 9);

    const debit = entry.type === 'invoice' ? inrFormat(entry.amount) : '';
    const credit = entry.type === 'receipt' ? inrFormat(entry.amount) : '';
    const balText = `${inrFormat(Math.abs(entry.balance))} ${entry.balance >= 0 ? 'Dr' : 'Cr'}`;
    const balColor: [number, number, number] = entry.balance >= 0 ? [225, 29, 72] : [5, 150, 105];

    setTextColor(pdf, SLATE8);
    pdf.setFont(FONT, 'normal');
    [entry.date, entry.ref || '—', entry.description].forEach((val, i) => {
      pdf.text(val.slice(0, i === 2 ? 36 : 18), colXs[i] + 2, y + 6);
    });

    if (debit) {
      setTextColor(pdf, [225, 29, 72]);
      pdf.setFont(FONT, 'bold');
      pdf.text(debit, colXs[3] + colWidths[3] - 2, y + 6, { align: 'right' });
    }
    if (credit) {
      setTextColor(pdf, [5, 150, 105]);
      pdf.setFont(FONT, 'bold');
      pdf.text(credit, colXs[4] + colWidths[4] - 2, y + 6, { align: 'right' });
    }
    setTextColor(pdf, balColor);
    pdf.setFont(FONT, 'bold');
    pdf.text(balText, balX + balW - 2, y + 6, { align: 'right' });
    y += 9;
  });

  if (entries.length === 0) {
    pdf.setFont(FONT, 'normal');
    pdf.setFontSize(9);
    setTextColor(pdf, SLATE5);
    pdf.text('No transactions found for the selected period.', W / 2, y + 10, { align: 'center' });
    y += 20;
  }

  // ── Summary footer ──
  y += 6;
  if (y + 22 > 272) { pdf.addPage(); y = 20; }

  setFillColor(pdf, LIGHT_BG);
  pdf.rect(margin, y, contentW, 22, 'F');
  setDrawColor(pdf, SLATE3);
  pdf.setLineWidth(0.4);
  pdf.rect(margin, y, contentW, 22);

  const summaryData: [string, string, [number, number, number]][] = [
    ['Total Invoiced', inrFormat(totalInvoiced), [225, 29, 72]],
    ['Total Received', inrFormat(totalReceived), [5, 150, 105]],
    ['Outstanding', inrFormat(Math.abs(totalInvoiced - totalReceived)), totalInvoiced >= totalReceived ? [225, 29, 72] : [5, 150, 105]],
  ];
  const sumColW = contentW / 3;
  summaryData.forEach(([label, val, color], i) => {
    const sx = margin + i * sumColW + sumColW / 2;
    pdf.setFont(FONT, 'normal');
    pdf.setFontSize(7.5);
    setTextColor(pdf, SLATE5);
    pdf.text(label, sx, y + 7, { align: 'center' });
    pdf.setFont(FONT, 'bold');
    pdf.setFontSize(13);
    setTextColor(pdf, color);
    pdf.text(val, sx, y + 17, { align: 'center' });
  });

  addWatermark(pdf);
  pdf.save(`Ledger_${clientName}.pdf`);
}

export function generateGroupLedgerPDF(
  summaries: { clientName: string; totalInvoiced: number; totalReceived: number; outstanding: number }[],
  practiceName: string,
  dateFrom?: string,
  dateTo?: string,
): void {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const W = 210;
  const margin = 14;
  const contentW = W - margin * 2;
  let y = 0;

  setFillColor(pdf, SLATE8);
  pdf.rect(0, 0, W, 32, 'F');
  pdf.setFont(FONT, 'bold');
  pdf.setFontSize(18);
  setTextColor(pdf, WHITE);
  pdf.text('GROUP LEDGER SUMMARY', margin, 16);
  pdf.setFont(FONT, 'normal');
  pdf.setFontSize(8.5);
  pdf.text(practiceName, margin, 25);
  const period = `${dateFrom || 'All time'} to ${dateTo || 'Present'}`;
  pdf.text(period, W - margin, 25, { align: 'right' });

  y = 42;

  // ── Table header ──
  setFillColor(pdf, SLATE8);
  pdf.rect(margin, y, contentW, 8, 'F');
  pdf.setFont(FONT, 'bold');
  pdf.setFontSize(8);
  setTextColor(pdf, WHITE);
  const colW = [contentW * 0.4, contentW * 0.2, contentW * 0.2, contentW * 0.2];
  const colXArr = [margin, margin + colW[0], margin + colW[0] + colW[1], margin + colW[0] + colW[1] + colW[2]];
  pdf.text('Client Name', colXArr[0] + 3, y + 5.5);
  pdf.text('Invoiced (₹)', colXArr[1] + colW[1] - 2, y + 5.5, { align: 'right' });
  pdf.text('Received (₹)', colXArr[2] + colW[2] - 2, y + 5.5, { align: 'right' });
  pdf.text('Outstanding (₹)', colXArr[3] + colW[3] - 2, y + 5.5, { align: 'right' });
  y += 8;

  let grandInv = 0, grandRec = 0;
  summaries.forEach((s, idx) => {
    if (y + 9 > 272) { pdf.addPage(); y = 16; }
    const rowBg: [number, number, number] = idx % 2 === 0 ? [255, 255, 255] : [249, 250, 251];
    setFillColor(pdf, rowBg);
    pdf.rect(margin, y, contentW, 9, 'F');
    setDrawColor(pdf, [226, 232, 240]);
    pdf.setLineWidth(0.2);
    pdf.line(margin, y + 9, margin + contentW, y + 9);

    pdf.setFont(FONT, 'bold');
    pdf.setFontSize(8.5);
    setTextColor(pdf, SLATE8);
    pdf.text(s.clientName, colXArr[0] + 3, y + 6);
    setTextColor(pdf, [225, 29, 72]);
    pdf.text(inrFormat(s.totalInvoiced), colXArr[1] + colW[1] - 2, y + 6, { align: 'right' });
    setTextColor(pdf, [5, 150, 105]);
    pdf.text(inrFormat(s.totalReceived), colXArr[2] + colW[2] - 2, y + 6, { align: 'right' });
    setTextColor(pdf, s.outstanding >= 0 ? [225, 29, 72] : [5, 150, 105]);
    pdf.text(
      inrFormat(Math.abs(s.outstanding)) + (s.outstanding >= 0 ? ' Dr' : ' Cr'),
      colXArr[3] + colW[3] - 2, y + 6, { align: 'right' }
    );
    grandInv += s.totalInvoiced;
    grandRec += s.totalReceived;
    y += 9;
  });

  // ── Grand total ──
  y += 2;
  if (y + 12 > 272) { pdf.addPage(); y = 16; }
  setFillColor(pdf, SLATE8);
  pdf.rect(margin, y, contentW, 11, 'F');
  pdf.setFont(FONT, 'bold');
  pdf.setFontSize(9);
  setTextColor(pdf, WHITE);
  pdf.text('GRAND TOTAL', colXArr[0] + 3, y + 7.5);
  pdf.text(inrFormat(grandInv), colXArr[1] + colW[1] - 2, y + 7.5, { align: 'right' });
  pdf.text(inrFormat(grandRec), colXArr[2] + colW[2] - 2, y + 7.5, { align: 'right' });
  const grandOut = grandInv - grandRec;
  pdf.text(
    inrFormat(Math.abs(grandOut)) + (grandOut >= 0 ? ' Dr' : ' Cr'),
    colXArr[3] + colW[3] - 2, y + 7.5, { align: 'right' }
  );

  addWatermark(pdf);
  pdf.save(`Group_Ledger_${new Date().toISOString().split('T')[0]}.pdf`);
}
